spring:
  application:
    name: ag-gate
zuul:
  prefix: /api  #拦截所有以api开头的的请求都进过zuul路由

  routes: # todo 路由表定义
    user-center:
        path: /uc/**
        serviceId: user-center

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8765



